api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Core/Domain/Entity'
            - '%kernel.project_dir%/src/Core/Application/Command'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
