framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - validation
                    - doctrine_transaction
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - validation

        transports:
            async: 'doctrine://default'

        routing:
            # EVENTS should never be processed async to allow for easy debug. It's not critical performance
            # wise to process them async but it is critical to persist all the effects in single transaction
            # Some COMMAND can be processed async to gain performance
