monolog:
    handlers:
        all:
            type: rotating_file
            path: "%kernel.logs_dir%/app.log"
            level: info

        console:
            type:   console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
