services:
    _defaults:
        autowire: true
        autoconfigure: true

    Kodzila\Core\Domain\Policy\:
        resource: './Domain/Policy/*'

    Kodzila\Core\Application\Handler\:
        resource: './Application/Handler/*'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: command.bus }

    Kodzila\Core\Presentation\:
        resource: './Presentation/*'

    Kodzila\Core\Presentation\Definition\JwtSwaggerDecorator:
        decorates: 'api_platform.openapi.factory'
        autoconfigure: false
